# Generated by Django 4.1.1 on 2022-09-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0005_alter_tarefa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'alta'), ('media', 'média'), ('baixa', 'baixa')], max_length=5),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('em andamento', 'em andamento'), ('pendente', 'pendente'), ('concluída', 'concluída')], max_length=12),
        ),
    ]
