# Generated by Django 4.1.1 on 2022-09-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0006_alter_tarefa_prioridade_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('em andamento', 'em andamento'), ('pendente', 'pendente'), ('concluída', 'concluída')], default='em andamento', max_length=12),
        ),
    ]
